version: "3"

services:
  localhost:
    image: teamadeptstation/ubuntuphpdev
    restart: 'always'
    ports:
      - '80:80'
    volumes: 
      - ./www:/var/www/html
      - ./data/mysql:/var/lib/mysql
      - ./logs/apache:/var/log/apache2
      - ./logs/mysql:/var/log/mysql